### ISSUE TITLE
30 second delay Switchbot Curtain

### ISSUE THREAD

**Issue by uffe6** [AdyRock/com.switchbot#35]
Hello. I have connected my homey pro directly to my two SwitchBot curtains. The connections works fine. My homey is Approx 4-5 meters away. And only one wall between. 

When I connect the device directly to my mobile via the switchbot. The curtain works flawlessly. Now to my problem.

I have a 30 seconds delay from giving the command to when the curtain is opening or closing. And often I get the “3000ms timed out” notification in homey. It always works and the curtain does want I want. But always with 30 seconds delay. If I try another command within these 30 seconds usually the command stacks up. And the second command takes another 30 sec before it’s received by the switchbot. I’ll add my log below. And hopefully you can figure out what might be the issue?  Thanks rgds Ulf. 

*  2022-08-14T08:18:06.214Z
!!!!!! Catch 2: Gardiner Sovrum: BLE Timeout
Error: BLE Timeout
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/ble.js:130:32)
    at BlePeripheral.discoverServices (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1114)
    at BlePeripheral.getService (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1544)
    at CurtainsBLEDevice._operateCurtainsLoop (/drivers/curtains_ble/device.js:250:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CurtainsBLEDevice._operateCurtain (/drivers/curtains_ble/device.js:194:28)
    at async CurtainsBLEDevice._onSetCapabilityValue (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:2134)

* 2022-08-14T08:18:06.234Z
!!!!!! Retry command (2 of 3) for Gardiner Sovrum in 2 seconds

* 2022-08-14T08:18:53.779Z
!!!!!! Catch 2: Gardiner Sovrum: BLE Timeout
Error: BLE Timeout
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/ble.js:130:32)
    at BlePeripheral.discoverServices (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1114)
    at BlePeripheral.getService (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1544)
    at CurtainsBLEDevice._operateCurtainsLoop (/drivers/curtains_ble/device.js:250:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CurtainsBLEDevice._operateCurtain (/drivers/curtains_ble/device.js:194:28)
    at async CurtainsBLEDevice._onSetCapabilityValue (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:2134)

* 2022-08-14T08:18:53.806Z
!!!!!! Retry command (2 of 3) for Gardiner Sovrum in 2 seconds

* 2022-08-14T08:19:55.120Z
!!!!!! Catch 2: Gardiner Sovrum: BLE Timeout
Error: BLE Timeout
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/ble.js:130:32)
    at BlePeripheral.discoverServices (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1114)
    at BlePeripheral.getService (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1544)
    at CurtainsBLEDevice._operateCurtainsLoop (/drivers/curtains_ble/device.js:250:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CurtainsBLEDevice._operateCurtain (/drivers/curtains_ble/device.js:194:28)
    at async CurtainsBLEDevice._onSetCapabilityValue (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:2134)

* 2022-08-14T08:19:55.136Z
!!!!!! Retry command (2 of 3) for Gardiner Sovrum in 2 seconds

* 2022-08-14T08:37:16.870Z
!!!!!! Catch 2: Gardiner Sovrum: BLE Timeout
Error: BLE Timeout
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/ble.js:130:32)
    at BlePeripheral.discoverServices (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1114)
    at BlePeripheral.getService (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1544)
    at CurtainsBLEDevice._operateCurtainsLoop (/drivers/curtains_ble/device.js:250:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CurtainsBLEDevice._operateCurtain (/drivers/curtains_ble/device.js:194:28)
    at async CurtainsBLEDevice._onSetCapabilityValue (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:2134)

* 2022-08-14T08:37:16.903Z
!!!!!! Retry command (2 of 3) for Gardiner Sovrum in 2 seconds

* 2022-08-14T08:42:05.236Z
!!!!!! Catch 2: Gardiner Sovrum: BLE Timeout
Error: BLE Timeout
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/ble.js:130:32)
    at BlePeripheral.discoverServices (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1114)
    at BlePeripheral.getService (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1544)
    at CurtainsBLEDevice._operateCurtainsLoop (/drivers/curtains_ble/device.js:250:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CurtainsBLEDevice._operateCurtain (/drivers/curtains_ble/device.js:194:28)
    at async CurtainsBLEDevice._onSetCapabilityValue (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:2134)

* 2022-08-14T08:42:05.257Z
!!!!!! Retry command (2 of 3) for Gardiner Sovrum in 2 seconds

**Comment by AdyRock** [comment]
So, the logs are showing BLE timeout, which means the Homey BLE couldn't connect to the device. It seems that it manages to send the command on the third retry. The BLE on Homey is not great although some are better than others.
If you can move Homey closer, in the same room, do you still see the problem?
I have one Homey that struggles to control the SwitchBot curtains via BLE when they are only 10cm away, but my other one can  just about about cope with about 2 meters in the next room.
That is one reason why I developed my own BLE hub with ESP32 devices, their range is about 4 times that of my best Homey. Also, they pass on status changes within 1 to 2 seconds, were Homey is limited to 30 second polling. If you want to purchase some modules from Amazon, my code for them is on GitHub.
The other option is to get a SwitchBot hub and control them via that.

**Comment by uffe6** [comment]
Thanks for your fast reply. Yeah I played around with the distance of the homey. And yes. That was the problem. I probably have to for for your solution with the EPS32 solution.

Is there a step by step guide for a newbie like me in order to get that ESP32 solution in place?

Thanks again!

Rgds Ulf

**Comment by AdyRock** [comment]
There are instructions in the readme https://github.com/AdyRock/SwitchBotBLEHub
