### ISSUE TITLE
curtains 3 not doing anything after connecting

### ISSUE THREAD

**Issue by vanderwees** [AdyRock/com.switchbot#81]
After reading #79 and updating to the latest test version, I could connect two Switchbot Curtain Rod 3's over BLE and read things like battery state. However, I don't get them to move anywhere, and mostly I get either timeouts or "Still sending previous command for [Mac address]. 

Any hints to what to do, or what could be wrong?

**Comment by vanderwees** [comment]
I'd send a diagnostic rapport 29b40703-1226-4c10-9441-d7f9f0976341

I see this error, which might mean I'm to far away from the device, so I'll test that
===========

2023-09-16T15:01:39.491Z
!!!!!! Peripheral Not Found: c8342fe2a3a4
Error: Peripheral Not Found: c8342fe2a3a4
    at Remote Process
    at HomeyClient.emit (/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23)
    at ManagerBLE.find (/node_modules/@athombv/homey-apps-sdk-v3/manager/ble.js:104:47)
    at CurtainsBLEDevice.getDeviceValues (/app/drivers/curtains_ble/device.js:334:63)
    at MyApp.onBLEPoll (/app/app.js:984:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by vanderwees** [comment]
After changing the homeys location, I'm now stuck with a "No OAuth2 Client Found" error

**Comment by AdyRock** [comment]
I think you are on the right track about the distance as Homey does have a short range. 
The OAuth error means you haven't connected to the Switchbot cloud API and is normal to see in certain places, so could you explain where you see it?

**Comment by vanderwees** [comment]
Thanks for your quick reply.

It seems homey can communicate, as it sees the battery. It is also not veeery far away (3m). I see this error in the app config when I'm clicking on Get Status => read status, and sometimes also in the Get HUB devices.

**Comment by AdyRock** [comment]
The status information is broadcast on a regular basis, so there is a good chance that Homey will get it at some point. 
To control a device, Homey has to find the device at that exact moment, send a command to connect to the device and then send the control command. What rssi value do you see?
If it's above 60 then communications will be sketchy, especially if there are other BLE devices around.

**Comment by vanderwees** [comment]
Both around -50dB

**Comment by vanderwees** [comment]
I put homey at 1,5m, RSSI is about -35/40dB, did a reconnect and still have the same problem, although I can see the devices under settings>Detected, I get the oauth error under settings>Get status

**Comment by AdyRock** [comment]
The OAuth error is unrelated. If you were connected via a Switchbot hub, then I would be concerned, but as you are using BLE it is irrelevant. 
I have a Homey 2018 and that works really well via BLE. Both my Homey 2019 and Homey 2023 are less reliable, so I use an ESP32 running my code as a bridge. However I did switch that off while I was testing the update. When testing, my HP2019 was about 2m away from the curtains and I was able to control them around 50% of the attempts. With my ESP32 module it would work 100% and that was about 4m away in a different room. 
I'm not sure how technically minded you are, but if you want to purchase an ESP32, they are about €15 on Amazon, then my code is on my GitHub account and free to use.

**Comment by vanderwees** [comment]
https://github.com/AdyRock/SwitchBotBLEHub
Do you mean this one?

I think I still have some esp32 laying around somewhere, so I'll give that a try and keep you posted.

**Comment by AdyRock** [comment]
Yes, that's the one. I have had some reports to say it needs to be restart after a while because it stops working, but I haven't found that myself.

**Comment by vanderwees** [comment]
So that was some fun to play around with. Got the esp32 flashed and Connected to my wlan, I can see the esp32 can see both the Curtains 3, and I'd readd them to my Homey using the Curtains (BLE) option. However, still nothing is happening. I have no clue anymore.

**Comment by AdyRock** [comment]
Could you send the information log from the app settings.

**Comment by vanderwees** [comment]
Done under ID: b40fd8f6-0129-46f1-a5bd-4dd2fb91aa1c

**Comment by vanderwees** [comment]
I've seen a new test version, and tested using that, but sadly I'm still having no movement whatsoever

**Comment by vanderwees** [comment]
Any more ideas? Would you be open to do a debug session together?

**Comment by AdyRock** [comment]
I'm on holiday at the moment so have no access to code, but could you send me the Information log from the app settings page. 
Are you using BLE or a Switchbot hub?

**Comment by AdyRock** [comment]
I have just seen some logs. Are they from you?

**Comment by vanderwees** [comment]
Yes, i send them about 12-14 hours ago, sadly I dont have the code from yesterday. I resubmitted under 38b50f16-75ab-45b4-ad4e-cd035cfce37b.

Have a nice holiday :)

**Comment by AdyRock** [comment]
Ah, OK I don't see the app diagnostics codes as they go to SwitchBot. 
The logs I need are from the app settings page as they get sent to me.

**Comment by vanderwees** [comment]
I just sent them. I couldnt send logs from the status page due to the Oauth2 error.

**Comment by vanderwees** [comment]
Any news? :)

**Comment by AdyRock** [comment]
I will be back from holiday tomorrow so I will look then.
